name: Docker Image CI
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-build.yml
      - Dockerfile
      - README.md
      - scripts/app.sh
      - scripts/entrypoint.sh
      - source/app.py
jobs:
  docker_images:
    runs-on: ubuntu-latest
    name: Build and push image
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.0.2

      - name: Login to dockerhub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.3.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/unifi-protect-timelapse:latest
          
      - name: Get image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  docker_description:
    runs-on: ubuntu-latest
    name: Update dockerhub description
    needs: docker_images
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.0.2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/unifi-protect-timelapse